//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string DART_RIGHT = "dart_right";
        
        public const string TIME = "time";
        
        public const string CORRECT_LEFT = "correct_left";
        
        public const string TOUCH_RIGHT = "touch_right";
        
        public const string WRONG_LEFT = "wrong_left";
        
        public const string DART_SHOT_LEFT = "dart_shot_left";
        
        public const string FAIL = "fail";
        
        public const string DART_LEFT = "dart_left";
        
        public const string WRONG_RIGHT = "wrong_right";
        
        public const string CORRECT_RIGHT = "correct_right";
        
        public const string CLEAR = "clear";
        
        public const string TOUCH_LEFT = "touch_left";
        
        public const string DART_SHOT_RIGHT = "dart_shot_right";
    }
}
